'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("")> _
    Public Property ArchiveFolderPath() As String
        Get
            Return CType(Me("ArchiveFolderPath"), String)
        End Get
        Set
            Me("ArchiveFolderPath") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("Local")> _
    Public Property ParseMode() As String
        Get
            Return CType(Me("ParseMode"), String)
        End Get
        Set
            Me("ParseMode") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
    Public Property OcrEnabled() As Boolean
        Get
            Return CType(Me("OcrEnabled"), Boolean)
        End Get
        Set
            Me("OcrEnabled") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("")> _
    Public Property BaiduApiKey() As String
        Get
            Return CType(Me("BaiduApiKey"), String)
        End Get
        Set
            Me("BaiduApiKey") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("")> _
    Public Property BaiduSecretKey() As String
        Get
            Return CType(Me("BaiduSecretKey"), String)
        End Get
        Set
            Me("BaiduSecretKey") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("https://aip.baidubce.com/rest/2.0/ocr/v1/multiple_invoice")> _
    Public Property BaiduOcrApiUrl() As String
        Get
            Return CType(Me("BaiduOcrApiUrl"), String)
        End Get
        Set
            Me("BaiduOcrApiUrl") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("https://aip.baidubce.com/oauth/2.0/token")> _
    Public Property BaiduTokenUrl() As String
        Get
            Return CType(Me("BaiduTokenUrl"), String)
        End Get
        Set
            Me("BaiduTokenUrl") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("30000")> _
    Public Property OcrTimeoutMs() As Integer
        Get
            Return CType(Me("OcrTimeoutMs"), Integer)
        End Get
        Set
            Me("OcrTimeoutMs") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property OcrReturnProbability() As Boolean
        Get
            Return CType(Me("OcrReturnProbability"), Boolean)
        End Get
        Set
            Me("OcrReturnProbability") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
    Public Property OcrReturnLocation() As Boolean
        Get
            Return CType(Me("OcrReturnLocation"), Boolean)
        End Get
        Set
            Me("OcrReturnLocation") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
    Public Property OcrVerifyParameter() As Boolean
        Get
            Return CType(Me("OcrVerifyParameter"), Boolean)
        End Get
        Set
            Me("OcrVerifyParameter") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("1")> _
    Public Property OcrMaxPages() As Integer
        Get
            Return CType(Me("OcrMaxPages"), Integer)
        End Get
        Set
            Me("OcrMaxPages") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property PreferLocalParse() As Boolean
        Get
            Return CType(Me("PreferLocalParse"), Boolean)
        End Get
        Set
            Me("PreferLocalParse") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property AutoFallbackToOcr() As Boolean
        Get
            Return CType(Me("AutoFallbackToOcr"), Boolean)
        End Get
        Set
            Me("AutoFallbackToOcr") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("{开票日期}_{销售方名称}_{发票号码}_{价税合计}")> _
    Public Property InvoiceNameTemplate() As String
        Get
            Return CType(Me("InvoiceNameTemplate"), String)
        End Get
        Set
            Me("InvoiceNameTemplate") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("{出发日期}_{乘车人}_{起点}-{终点}_{订单号}_{行程金额}")> _
    Public Property TripNameTemplate() As String
        Get
            Return CType(Me("TripNameTemplate"), String)
        End Get
        Set
            Me("TripNameTemplate") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("未识别票据_{原附件名}_{时间戳}")> _
    Public Property UnknownNameTemplate() As String
        Get
            Return CType(Me("UnknownNameTemplate"), String)
        End Get
        Set
            Me("UnknownNameTemplate") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("{乘车日期}_{金额}_{出发地点}_{到达地点}")> _
    Public Property UnifiedNameTemplate() As String
        Get
            Return CType(Me("UnifiedNameTemplate"), String)
        End Get
        Set
            Me("UnifiedNameTemplate") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("{开票日期}_{金额}_{销售方名称}")> _
    Public Property GeneralInvoiceNameTemplate() As String
        Get
            Return CType(Me("GeneralInvoiceNameTemplate"), String)
        End Get
        Set
            Me("GeneralInvoiceNameTemplate") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.iWorkhelper.MySettings
            Get
                Return Global.iWorkhelper.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
